language: java
sudo: required

services:
  - docker

before_install:
  - docker network create --subnet 172.18.0.0/16 demo-app
  - cd app2
  - gradle clean buildDocker
  - cd ../app1/
  - gradle clean buildDocker
  - ./rundocker.sh &
  - cd ../app2
  - ./rundocker.sh &
